# trunk-ignore(ruff/D400)
# trunk-ignore(ruff/D415)
"""users and verifications table

Revision ID: 63eea9081df8
Revises: 
Create Date: 2023-05-31 12:29:51.576666

"""
# trunk-ignore(ruff/F401)
import sqlalchemy as sa

# trunk-ignore(ruff/F401)
from alembic import op

# revision identifiers, used by Alembic.
revision = "63eea9081df8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
