# trunk-ignore(ruff/D400)
# trunk-ignore(ruff/D415)
"""added is_oauth column to users table

Revision ID: 1da97c81acd7
Revises: 838ee68e6113
Create Date: 2023-03-27 12:02:28.844237

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1da97c81acd7"
down_revision = "838ee68e6113"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_oauth", sa.Boolean(), server_default=sa.text("FALSE"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_oauth")
    # ### end Alembic commands ###
