# trunk-ignore(ruff/D400)
# trunk-ignore(ruff/D415)
"""email verification

Revision ID: 838ee68e6113
Revises: 9e23355c67d5
Create Date: 2023-03-16 18:08:29.895785

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "838ee68e6113"
down_revision = "9e23355c67d5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verifications",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token", sa.Integer(), nullable=False, unique=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_verifications_user_id"), "verifications", ["user_id"], unique=False
    )
    op.add_column(
        "users",
        sa.Column(
            "is_verified", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified")
    op.drop_index(op.f("ix_verifications_user_id"), table_name="verifications")
    op.drop_table("verifications")
    # ### end Alembic commands ###
